# Generated by Django 5.1.1 on 2024-11-20 08:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChitGroup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_name', models.CharField(max_length=100)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('installment_amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('months', models.PositiveIntegerField()),
                ('members_count', models.PositiveIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Subscriber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('phone', models.CharField(max_length=15)),
                ('address', models.TextField()),
                ('email', models.EmailField(max_length=254)),
                ('ticket_number', models.CharField(blank=True, max_length=100, null=True)),
                ('group_name', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subscribers', to='chit_fund_app.chitgroup')),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('payment_date', models.DateField()),
                ('chit_group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_fund_app.chitgroup')),
                ('subscriber', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='chit_fund_app.subscriber')),
            ],
        ),
    ]
