# Generated by Django 5.1.1 on 2024-11-21 17:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chit_fund_app', '0003_payment_arrears_payment_cheque_details_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='payment',
            name='amount_in_words',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='payment',
            name='installment_month',
            field=models.CharField(blank=True, max_length=7, null=True),
        ),
    ]
